### ISSUE TITLE
Prevent keychain access when user is not logged in

### ISSUE THREAD

**Issue by dreese** [Electrode-iOS/ELKeychain#1]
Probably best to use `kSecAttrAccessibleWhenUnlocked` in order to prevent access except while a user is logged in. This has the drawback that apps running in the background cannot access the keychain during this time either.

**Comment by angelodipaolo** [comment]
The ELKeychain API supports an optional parameter, `accessControl`, that enables you to specify the access control policy of the item being stored in the keychain.

```
let keychain = Keychain(service: "druidia-airshield")
let accessControl = try? AccessControl(protection: .whenPasscodeSetThisDeviceOnly, policy: .UserPresence)
try! keychain.set("12345", account: "king-roland", accessControl: accessControl)
```

**Comment by dreese** [comment]
I see that you added this on Jun 29. Cool.
